name: Arcano5
description: Filosofia, literatura e cotidiano, por Marcos Ramon
meta_description: "Filosofia, literatura e cotidiano, por Marcos Ramon"

markdown:         kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  pygments: true
  
logo: false
paginate: 15
baseurl: /arcano5
domain_name: 
google_analytics: 

# Permalinks
permalink:        /:title/

# Details for the RSS feed generator
url:            
author:         'Marcos Ramon'
