name: Arcano5
description: Filosofia e cotidiano, por Marcos Ramon
meta_description: "Filosofia, cotidiano, arte e tecnologia"

markdown:         kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  pygments: true
  
logo: false
paginate: 15
baseurl: /
domain_name: 
google_analytics: 'UA-38260251-2'

# Permalinks
permalink:        /:title/

# Details for the RSS feed generator
url:            
author:         'Marcos Ramon'
